import { StyleSheet, Platform } from 'react-native';

const styles = StyleSheet.create({
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'white',
    marginHorizontal: 15,
    marginVertical: 10,
    borderRadius: 12,
    paddingHorizontal: 15,
    height: 55,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 5,
    marginTop: -30, 
  },
  searchIcon: {
    marginRight: 12,
  },
  searchInput: {
    flex: 1,
    height: '100%',
    fontSize: 16,
    color: '#2C3E50',
    // Remove focus outline on web
    ...Platform.select({
      web: {
        outlineStyle: 'none',
      },
      default: {},
    }) as any,
  },
  sectionContainer: {
    marginTop: 30,
  },
  sectionContainer1: {
    marginTop: 18,
  },
  sectionContainer2: {
    backgroundColor: '#E8F5E9',
  },
  sectionTitle: {
    fontSize: 16  ,
    fontWeight: 'medium',
    color: '#2C3E50',
    paddingHorizontal: 5,
    marginBottom: 10,
  },
  sectionTitle2: {
    fontSize: 16,
    fontWeight: 'medium',
    color: '#2C3E50',
    paddingHorizontal: 15,
    marginTop: 20,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 15,
    marginBottom: 10,
  },
  seeAllText: {
    color: '#95A5A6',
    fontSize: 14,
    fontWeight: '500',
  },
  sectionTitle3: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#2C3E50',
    paddingHorizontal: 15,
  },
  categoriesScrollView: {
    paddingHorizontal: 5,
  },
  categoryCard: {
    // width: 180,
    height: 60,
    borderRadius: 30,
    justifyContent: 'flex-start',
    alignItems: 'center',
    marginHorizontal: 8,
    flexDirection: 'row',
    backgroundColor: '#E8F5E9',
    paddingRight: 20,
    paddingLeft: 5,
    borderWidth: 1,
    borderColor: '#E0E0E0',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
    marginBottom: 10,
  },
  categoryIconContainer: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: '#f0fff2ff',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
  },
  categoryName: {
    color: '#2C3E50',
    fontWeight: '600',
    fontSize: 15,
  },
  categoryImage: {
    width: 50,
    height: 50,
  },
  quickServicesContainer: {
    // width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingHorizontal: 15,
    borderTopStartRadius: 50,
    borderTopEndRadius: 50,
    paddingVertical: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
    backgroundColor: '#4F7942',
    overflow: 'hidden',
  },
  quickServiceCard: {
    alignItems: 'center',
    marginTop: 10,
    marginBottom: 10,
  },
  quickServiceIconContainer: {
    backgroundColor: '#E8F5E9',
    width: 60,
    height: 60,
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 5,
  },
  quickServiceText: {
    fontSize: 12,
    color: 'white',
    fontWeight: '500',
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  herbalCategoriesContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    paddingHorizontal: 15,
    backgroundColor: '#E8F5E9',
    marginTop: 5,
  },
  herbalCategoryCard: {
    width: '48%',
    backgroundColor: 'white',
    borderRadius: 15,
    padding: 15,
    marginBottom: 15,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    marginTop: 5,
  },
  herbalCategoryName: {
    fontSize: 14,
    fontWeight: '600',
    color: '#2C3E50',
    textAlign: 'center',
    marginTop: 10,
  },
  herbalCategoryImage: {
    width: 80,
    height: 80,
  },
  featuredRemediesScroll: {
    paddingHorizontal: 5,
  },
  featuredRemedyCard: {
    width: 250,
    backgroundColor: 'white',
    borderRadius: 15,
    marginHorizontal: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    marginTop: 10,
  },
  featuredRemedyImagePlaceholder: {
    width: '100%',
    height: 150,
    borderTopLeftRadius: 15,
    borderTopRightRadius: 15,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#E8F5E9',
  },
  featuredRemedyContent: {
    padding: 15,
  },
  featuredRemedyTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#2C3E50',
    marginBottom: 5,
  },
  featuredRemedyDescription: {
    fontSize: 14,
    color: 'rgb(99, 99, 109)',
  },
  disabledCategoryCard: {
    opacity: 0.5,
    backgroundColor: '#F5F5F5',
    shadowOpacity: 0.05,
    elevation: 1,
  },
  disabledCategoryImage: {
    opacity: 0.5,
  },
  disabledCategoryName: {
    color: '#9E9E9E',
  },
  noDataText: {
    fontSize: 14,
    color: '#95A5A6',
    fontStyle: 'italic',
    paddingHorizontal: 15,
    marginTop: 5,
  },
  categoriesContent: {
    paddingRight: 20,
    alignItems: 'center',
  },
});

export default styles;